### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by krasin**
Hi Andrew,

Please, review this set of patches. I have updated install.sh and README to use llvm-config --libs instead of linking with libLLVM3.1svn.so (or, whatever version is installed).

Since llvm-config --libs is specifically designed for this purpose, it should work for every system.

### CODE REVIEW

**Comment by axw** [comment]
Hi krasin,

I had previously tried doing this, as I'd like to remove the shared library dependency on llgo. The reason why I've been able to get away with it is because I build LLVM with "--enable-shared" (sorry, probably should have documented that).

Unfortunately I found using "llvm-config --libs" didn't work, due to missing C++ dependencies (libstdc++). It also takes an enormous amount of time to link, so if this can work I'll happily make it the default, but probably with an option of dynamic linking to speed up development.

I can get gollvm to build by adding "-lstdc++" to the CGO_LDFLAGS, but llgo complains about missing symbols. I'm curious as to how you could link without at least adding libstdc++.

I'm going to try building the revision of LLVM you mentioned to see if it's just my tree that is out of whack.

**Comment by axw** [comment]
No dice. Built (well, tried and failed) against a fresh LLVM at r152977.

The only explanation I can think of is that you had built gollvm first against the shared library, then modified the install.sh and rebuilt without cleaning the pkg directory in $GOPATH. Since the source wouldn't have changed, install.sh wouldn't have done anything.

Apparently cgo doesn't support linking against static libraries anyway:
- https://groups.google.com/d/msg/golang-nuts/UoYT9Y8tRwE/e9SPcqlNUfYJ
- https://groups.google.com/d/msg/golang-nuts/ZHJV1H99Uzs/9HrQXW7qFHYJ

I'll leave this open till the discrepancy has been gotten to the bottom of, but I think I'll have to reject it due to the above.

**Comment by krasin** [comment]
Hi Andrew,

I build LLVM by the following way:

```
svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
mkdir llvm/cbuild
cd llvm/cbuild
cmake -DBUILD_SHARED_LIBS=true -DCMAKE_INSTALL_PREFIX=/usr ..
make -j16
sudo make install
```

After that, I try to install gollvm. It succeeds with my patches, but fails with install.sh, because libLLVM3.1svn.so is not built (probably, it is only generated  with configure/make build, not cmake).

Static linkage with libstdc++ is too painful to even consider it.

**Comment by krasin** [comment]
Huh!

building it with configure/make produces ./Release+Asserts/lib/libLLVM-3.1svn.so

I can live with this, although, configure/make is about 3x slower and is discouraged by LLVM community. 

You may want to pick up f6c3f8e commit, which is not about --libs.

**Comment by axw** [comment]
Thanks for clarifying; I hadn't previously used cmake to build LLVM. The world makes sense again.

I'll have to have another think about it. The binary distribution apparently doesn't ship the single .so either. I will definitely cherry pick f6c3f8e later.

**Comment by axw** [comment]
I've merged in f6c3f8e. I'm not really seeing a benefit of depending on the cmake build, other than the faster builds of LLVM itself.

I'm going to close this for now.

**Pull request closed without merging**
