### PR TITLE
Introduce DIBuilder wrapper

### PR DESCRIPTION
**Pull request by axw**
Also, pull code out of llgo-dist to create go-llvm-dist.

### CODE REVIEW

**Comment by axw** [comment]
When building LLVM in Debug mode, CreateCompileUnit will assert/abort as DWARF_LANG_Go is outside the standard language range known to LLVM.

http://dwarfstd.org/ShowIssue.php?issue=101014.1&type=open

Will have to send a patch to LLVM.

**Comment by pcc** [comment]
That was one of the issues I ran into when I tested your patch against LLVM trunk.

The other was that one of the DIBuilder method signatures has changed between 3.4 and trunk.

I continue to believe that gollvm should track trunk by default. I'll send out my follow-trunk patch tonight and we can discuss there.

**Comment by axw** [comment]
Updated to LLVM trunk DIBuilder API, fixed various bugs found with LLVM in Debug+Asserts mode. Also, I've formatted the .h/.cpp with clang-format, default LLVM style.

**Comment by pcc** [comment]
LGTM with these changes, please merge afterwards.

**Comment by axw** [comment]
Done.

**Pull request merged**
